{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "b8798b45_d11eb838",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1468500
      },
      "writtenOn": "2023-11-17T11:33:33Z",
      "side": 1,
      "message": "LGTM",
      "revId": "d94a90a72521f48ac4ec449ca2cd60a0ce8c3902",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "3145d0db_35b6dc1a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1288325
      },
      "writtenOn": "2023-11-17T13:50:46Z",
      "side": 1,
      "message": "The failure is a Node.js flake which I happen to be fixing too in the upstream https://github.com/nodejs/node/pull/50735 - not sure what\u0027s the better next step here..",
      "revId": "d94a90a72521f48ac4ec449ca2cd60a0ce8c3902",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}